---
400: The server cannot or will not process the request.
401: You are not authorized to request this resource.
403: The server is refusing to respond to your request.
404: The page you are looking for was not found.
405: The server doesn't accept your request method.
406: The headers can't be accepted by the server.
407: The client must first authenticate itself with the proxy.
408: The server timed out waiting for the request.
409: The request could not be processed because of conflict.
410: The resource is no longer available and will not be available again.
411: The request did not specify the length of its content.
412: The server does not meet one of the preconditions.
413: The request is larger than the server is willing or able to process.
414: The URI provided was too long for the server to process.
415: The request has a media type which the server does not support.
416: The requested range can't be satisfied.
417: The server cannot meet the requirements of the Expect header.
422: The request was well-formed but was unable to be followed.
423: The resource that is being accessed is locked.
424: The request failed due to failure of a previous request.
426: The client should switch to a different protocol.
428: The origin server requires the request to be conditional.
429: The user has sent too many requests in a given amount of time.
431: The server is unwilling to process the request.
451: The request have been blocked because of legal reasons.
500: I messed it up, but this is not your fault.
501: The server does not recognize the request method.
502: The server received an invalid response from upstream.
503: The server is currently unavailable, this is a temporary state.
504: The server did not receive a timely response from upstream.
505: The server does not support the HTTP protocol version.
506: Transparent content negotiation results in a circular reference.
507: The server is unable to store the result of the request.
508: The server detected an infinite loop while processing the request.
510: Extensions to the request are required for the server to fulfil it.
511: The client needs to authenticate to gain network access.

...
